name = "sapporo-driving-support"
type = "javascript"
main = "src/index.js"
compatibility_date = "2026-09-11"

[env.production]
name = "sapporo-driving-support-prod"
routes = [
  { pattern = "sapporo-driving-support.pages.dev", zone_id = "" }
]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx", "index.html"]

[[build.upload]]
format = "service-worker"

[build.upload.rules]
type = "CompiledContentType"
globs = ["**/*.js"]
fallthrough = true

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.{html,css,svg,ico,json,txt,xml,webmanifest}"]
fallthrough = true

[env.production.build]
command = "npm run build"

[triggers.crons]

[observability]
enabled = true

[analytics]
enabled = true
